### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by abcdw** [JonWaltman/pcmpl-args.el#15]
Add a tag please, it will be easier for some linux distribution and PMs to package pcmpl-args.el

I will make a package for GNU Guix.

Thanks a lot for the work on this great emacs package!)

**Comment by CeleritasCelery** [comment]
I added the `0.1.2` tag to master.

**Comment by abcdw** [comment]
Thank you! I made a package, but I'll wait until #18 is merged before sending it to Guix, the PR has important fixes.

**Comment by CeleritasCelery** [comment]
minimum Emacs version has been moved to 25.1 and release tag has been updated to `0.1.3`.

**Comment by abcdw** [comment]
Troy Hinckley ***@***.***> writes:

> minimum Emacs version has been moved to 25.1 and release tag has been updated to `0.1.3`.

Thank you, but, unfortunately, I don't see any tags in the repository :(

**Comment by CeleritasCelery** [comment]
Sorry, forgot to push the tag.

**Comment by abcdw** [comment]
Thank you. Package is on the way to the Guix repository:
https://issues.guix.gnu.org/50003
