### ISSUE TITLE
ls autogenerated completion annotation is broken

### ISSUE THREAD

**Issue by abcdw** [JonWaltman/pcmpl-args.el#16]
For example -G in man page:
```
-G, --no-group
              in a long listing, don't print group names
```
but in the generated completion:
![image](https://user-images.githubusercontent.com/1218615/127288298-4402066d-bea2-4e00-8b72-83899dd4c70f.png)

Other commands also can be affected.

**Comment by xFA25E** [comment]
I think that the #4 is responsible. I've been having same issues here #11 . That is why I applied `col -b` to a parsed result, instead of applying it on result of `man` command. It seems that the man parser is relying on ^H characters.
