### ISSUE TITLE
pcmpl-args breaks environment variable completion

### ISSUE THREAD

**Issue by minad** [JonWaltman/pcmpl-args.el#22]
Possibly related to #19 

1. emacs -Q
2. eshell
3. Enter `echo $SHE TAB` -> completes
4. Load pcmpl-args
5. Enter `echo $SHE` -> no completion

This issue does not only affect echo but also other commands. `pcmpl-args` should try to opt out when completing variables.

**Comment by LemonBreezes** [comment]
So it turns out PComplete's API completely hands completion to the `pcomplete/*` argument, including whether the result of `$FORM` is used to generate completions (see the documentation of `pcomplete-here`). Therefore, I believe the solution is to look through the `pcmpl-args` API to see what the dynamic completion table functions are. I suspect that some of them have this `form-only` variable turned off. I don't think that `$FORM` expansion is necessary for all completions, but definitely `echo` and forms which take file name or directory name arguments should have form expansion enabled.

**Comment by LemonBreezes** [comment]
```
(defun +pcmpl--apply-expansions-a (&rest _)
  (run-hooks 'pcomplete-try-first-hook))

(dolist (pcmpl-args-pcomplete-function
         '(pcmpl-args-pcomplete
           pcmpl-args-pcomplete-on-help
           pcmpl-args-pcomplete-on-man))
  (advice-add pcmpl-args-pcomplete-function :before
              #'+pcmpl--apply-expansions-a))
```

This code snippet above fixes this issue for most of the `pcomplete/*` functions defined in this package, though there are some like `pcomplete/dd` which manually call `pcomplete-here*` (or perhaps other pcomplete-* functions) with `form-only` set to `t` which disables `$PREFIX` and other user-defined completion transformations.

**Comment by minad** [comment]
@CeleritasCelery Can you please reopen since the fix by @LemonBreezes was reverted for now, see #28. I think @LemonBreezes' fix is actually correct, we should maybe work around this on the level of the problematic eshell variable assignment function.

**Comment by LemonBreezes** [comment]
> @CeleritasCelery Can you please reopen since the fix by @LemonBreezes was reverted for now, see #28. I think @LemonBreezes' fix is actually correct, we should maybe work around this on the level of the problematic eshell variable assignment function.

I've been digging a bit and right now I have not found a special purpose for this variable assignment completion. You can't write `test="foo"` in Eshell like in Bash and this statement is not valid Lisp either. If there really is no purpose for this other than completing command arguments like for `dd if=...`, `ls --color=...`, and `make --makefile=...`, then the best option is to remove `eshell-complete-variable-assignment` for that function call.

**Comment by minad** [comment]
Yes, this sounds like an acceptable fix. But you may still want the assignment completion to take place sometimes when pcmpl-args does not take over? Could that happen?

**Comment by LemonBreezes** [comment]
> @CeleritasCelery Can you please reopen since the fix by @LemonBreezes was reverted for now, see #28. I think @LemonBreezes' fix is actually correct, we should maybe work around this on the level of the problematic eshell variable assignment function.

I propose:

```
(let ((pcomplete-try-first-hook (remq 'eshell-complete-variable-assignment
                                      pcomplete-try-first-hook)))
  (run-hooks 'pcomplete-try-first-hook))
```

**Comment by LemonBreezes** [comment]
> Yes, this sounds like an acceptable fix. But you may still want the assignment completion to take place sometimes when pcmpl-args does not take over? Could that happen?

Yes. I propose: 
```
(let ((pcomplete-try-first-hook (remq 'eshell-complete-variable-assignment
                                      pcomplete-try-first-hook)))
  (run-hooks 'pcomplete-try-first-hook))
```

**Comment by minad** [comment]
I think I wasn't precise above. I want the eshell assignment completion to also take place if the pcmpl-args assignment completion does not take over. If you remove the eshell variable completion function this cannot happen, so your proposal seems incomplete.

**Comment by LemonBreezes** [comment]
> I think I wasn't precise above. I want the eshell assignment completion to also take place if the pcmpl-args assignment completion does not take over. If you remove the eshell variable completion function this cannot happen, so your proposal seems incomplete.

My bad, I meant to say that in `pcmpl-args-pcomplete`, we should replace the new line from the last pull request, `(run-hooks 'pcomplete-try-first-hook)`, with
```
(let ((pcomplete-try-first-hook (remq 'eshell-complete-variable-assignment
                                      pcomplete-try-first-hook)))
  (run-hooks 'pcomplete-try-first-hook))
```

(On phone right now, beware typos)

**Comment by minad** [comment]
> My bad, I meant to say that in pcmpl-args-pcomplete, we should replace the new line from the last pull request, (run-hooks 'pcomplete-try-first-hook), with

Yes, I understood that. But it does not answer my question. The point is if in `pcmpl-args-pcomplete` the variable assignment expansion is not performed by `pcmpl-args-pcomplete` then `eshell-complete-variable-assignment` is not executed. As I already wrote, your proposal does not cater for this issue.

So maybe there is an even better solution where one checks if `pcmpl-args-pcomplete` does indeed complete the `=`. If that's the case, remove the eshell function. If not, then it should stay.

**Comment by LemonBreezes** [comment]
> > My bad, I meant to say that in pcmpl-args-pcomplete, we should replace the new line from the last pull request, (run-hooks 'pcomplete-try-first-hook), with
> 
> Yes, I understood that. But it does not answer my question. The point is if in `pcmpl-args-pcomplete` the variable assignment expansion is not performed by `pcmpl-args-pcomplete` then `eshell-complete-variable-assignment` is not executed. As I already wrote, your proposal does not cater for this issue.
> 
> So maybe there is an even better solution where one checks if `pcmpl-args-pcomplete` does indeed complete the `=`. If that's the case, remove the eshell function. If not, then it should stay.

In what situation would `pcmpl-args-pcomplete` not expand the variable assignment? The only one I can think of is if the `argspec` we compute/specify for the command is incorrect. However, in that case, wouldn't manually patching that command or fixing the parser be better? That way we have annotations as well.

**Comment by minad** [comment]
> In what situation would pcmpl-args-pcomplete not expand the variable assignment?

For example when the option does not specify a list of values, since it accepts more than a finite set. This is quite a common case, isn't it?

**Comment by LemonBreezes** [comment]
> > In what situation would pcmpl-args-pcomplete not expand the variable assignment?
> 
> For example when the option does not specify a list of values, since it accepts more than a finite set. This is quite a common case, isn't it?

I need to test this when I get home to find a solution. Would you please be able to provide an example?
