### ISSUE TITLE
Addition to NonGNU Elpa

### ISSUE THREAD

**Issue by minad** [JonWaltman/pcmpl-args.el#24]
I would like to propose this package for inclusion in NonGNU ELPA such that it is readily available on new Emacs installs. Recently a lot of essential packages got added there and pcmpl-args seems like a good fit. Corfu and Company already live in GNU ELPA, with the addition of pcmpl-args we can hopefully get a shell experience which is almost on par with fish only with Emacs components (for example eshell+pcmpl-args+corfu). Alternatively one could consider adding the package to GNU ELPA. This is possible if the main developers of this package have assigned the copyright to the FSF or are willing to do so.

**Comment by CeleritasCelery** [comment]
See #5.

**Comment by minad** [comment]
Okay, nongnu Elpa is a good solution then!

**Comment by CeleritasCelery** [comment]
Can you elaborate on the benefit of Non-GNU ELPA over MELPA?

**Comment by minad** [comment]
No significant benefit except that ELPA is available in Emacs without additional configuration. Furthermore ELPA focuses more on stability by distributing tagged versions, like MELPA stable.

**Comment by minad** [comment]
cc @skangas, who is currently adding many important packages to NonGNU ELPA.

**Comment by manuel-uberti** [comment]
I second @minad request, and also let me just say "thanks!" for this great package. I know that @phikal deals with NonGNU ELPA as well, maybe he can help in this regard.

**Comment by minad** [comment]
Added in https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?id=d99c2d0f4e53c83804bde186865fa166c516da4d.
