### ISSUE TITLE
git checkout: complete available branches

### ISSUE THREAD

**Issue by manuel-uberti** [JonWaltman/pcmpl-args.el#32]
First of all thanks for this package!

Would it be possible to mirror the usual output of `git checkout` + <kbd>TAB</kbd> on a terminal (e.g., GNOME Terminal) using Bash?

If I do:

- emacs -Q
- `M-x package-initialize`
- `(require 'pcmpl-args)`
- `M-x shell`
- `cd` into a git-controlled directory
- `git checkout` <kbd>TAB</kbd>

I get a `*Completions*` buffer with the contents of the directory I am in instead of the possible branches.

**Comment by CeleritasCelery** [comment]
checkout https://melpa.org/#/pcmpl-git

**Comment by manuel-uberti** [comment]
Thanks for the tip, I'll try that.
