### ISSUE TITLE
Contribute this to mainline GNU Emacs

### ISSUE THREAD

**Issue by skangas** [JonWaltman/pcmpl-args.el#5]
Please consider contributing this code for inclusion in mainline GNU Emacs.

I think it has general appeal and if it was available by default all Emacs users could benefit.  If you would like to do so, you could send an email to bug-gnu-emacs@gnu.org declaring your intention to contribute it.

You would also need to assign copyright to the Free Software Foundation, which is a (relatively) fast one-time process.  The reasons for why this requirement exists are explained here: https://www.gnu.org/licenses/why-assign.html

Thanks in advance for considering this request, and for the useful package.

**Comment by CeleritasCelery** [comment]
I don't know how feasible that is. @JonWaltman is the creator of this project and he claims copyright to it https://github.com/JonWaltman/pcmpl-args.el/blob/0b8a05fc6e370fa9c466250659619f8d6b53d446/pcmpl-args.el#L3

Jon would have to sign the copyright over to the FSF (which could be done) before I could consider contributing this (as well as the other contributors).
