### ISSUE TITLE
pass and parted completions

### ISSUE THREAD

**Issue by xFA25E** [JonWaltman/pcmpl-args.el#8]
Hey, I've made [pass and parted](https://github.com/xFA25E/nixpkgs-config/blob/8aa0e4c0523b57507eaf39690ca28d0df5ba20c2/emacs/pcmpl-args-extra.el) completions for pcmpl-args. Are you interested in adding them to pcmpl-args?

**Comment by CeleritasCelery** [comment]
I am! Could you open a PR?

**Comment by xFA25E** [comment]
Yes, I'll do it soon
